name: CI
on:
  push:
    branches:
      - dev
      - feature    
  pull_request:
  release:
    types:
      - staging
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  checkout_and_install:
    strategy:
      matrix:
        node: ["12.22.1", "14.16.1", "15.14.0", "16.1.0"]        
    runs-on: [self-hosted, linux, x64, gpu]    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies
        run: npm ci
  lint_and_tsc:
    needs: checkout_and_install
    runs-on: [self-hosted, linux, x64, gpu]
    steps:
      - name: Lint
        run: npm run lint
      - name: Check types
        run: npm run tsc
  build_and_test:
    needs: 
      - lint_and_tsc      
    runs-on: [self-hosted, linux, x64, gpu]
    steps:      
      - name: npm build, and test
        run: |
          npm run build --if-present
          npm test:unit      
  coverage:
    name: Coverage
    needs: 
      - build_and_test
    runs-on: [self-hosted, linux, x64, gpu]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: 15
      - run: npm ci
      - run: npm run test:coverage
      - uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
