name: CI
on:
  push:
    branches:
      - dev
      - feature    
  pull_request:
  release:
    types:
      - staging
  workflow_dispatch:    
jobs:
  checkout_and_install:
    strategy:
      matrix:
        node: ["12.22.1", "14.16.1", "15.14.0", "16.1.0"]        
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies
        run: npm ci
      - name: Installing nyc
        run: npm install nyc --save-dev
  build_and_test:
    needs: 
      - checkout_and_install      
    runs-on: ubuntu-latest
    steps:      
      - name: npm build, and test
        run: |
          npm run build --if-present
          npm test
  lint:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Installing node_modules
        run: npm install eslint --global
      - name: Install Yarn
        run: npm install -g yarn
      - name: Run lint
        run: yarn run eslint --init     
  coverage:
    name: Coverage
    needs: 
      - lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: 15
      - name: Installing coverage
        run: npm install check-code-coverage 
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload coverage to Codecov 
        uses: codecov/codecov-action@v1
  duplicate_code_detection:
    name: Check for duplicate code
    needs: 
      - coverage
    runs-on: ubuntu-latest
    steps:
    - uses: platisd/duplicate-code-detection-tool@master
      with:
        directories: "test/"
        # Only examine .h and .cpp files
        file_extensions: "sh, js"
        # Only report similarities above 5%
        ignore_below: 5
        # If a file is more than 70% similar to another, then the job fails
        fail_above: 70
        # If a file is more than 15% similar to another, show a warning symbol in the report
        warn_above: 15    
  sonar_scan:
    name: Detect bugs, vulnerabilities and code smells
    needs: 
      - duplicate_code_detection
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
      # Triggering SonarQube analysis as results of it are required by Quality Gate check
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
    - name: SonarQube Quality Gate check
      uses: sonarsource/sonarqube-quality-gate-action@master
      with:
       scanMetadataReportFile: target/sonar/report-task.txt
      # Force to fail step after specific time
      timeout-minutes: 5
      env:
       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  upload_to_artifactory:
    name: Artifactory
    needs: coverage
    runs-on: ubuntu-latest
    steps:
      - name: Archive staging artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-without-markdown
          path: |
            dist
            !dist/**/*.md
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: output/test/code-coverage.html
  publish_to_staging:
    name: Publish to staging    
    needs:
      - upload_to_artifactory 
    runs-on: ubuntu-latest
    if: github.event.action == 'Staging'
    name: Staging
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2.4.0
          with:
            registry-url: https://registry.npmjs.org/
            node-version: 15
        - run: npm ci
        - run: npm publish --access restricted
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
   
  publish_to_production:
    name: Publish to production    
    needs:
      - upload_to_artifactory      
    if: github.event.action == 'Production'
    name: Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.0
        with:
          registry-url: https://registry.npmjs.org/
          node-version: 15
      - run: npm ci
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
