name: CI
on:
  push:
    branches:
      - dev
      - feature    
  pull_request:
  release:
    types:
      - staging
  workflow_dispatch:    
jobs:
  checkout_and_install:
    strategy:
      matrix:
        node: ["12.22.1", "14.16.1", "15.14.0", "16.1.0"]        
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies
        run: npm ci
  lint_and_tsc:
    needs: checkout_and_install
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        run: npm run lint
      - name: Check types
        run: npm run tsc
  build_and_test:
    needs: 
      - lint_and_tsc      
    runs-on: ubuntu-latest
    steps:      
      - name: npm build, and test
        run: |
          npm run build --if-present
          npm test:unit      
  coverage:
    name: Coverage
    needs: 
      - build_and_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: 15
      - run: npm ci
      - run: npm run test:coverage
      - uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
  sonar_scan:
    name: Detect bugs, vulnerabilities and code smells
    needs: 
      - build_and_test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
      # Triggering SonarQube analysis as results of it are required by Quality Gate check
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
    - name: SonarQube Quality Gate check
      uses: sonarsource/sonarqube-quality-gate-action@master
      with:
       scanMetadataReportFile: target/sonar/report-task.txt
      # Force to fail step after specific time
      timeout-minutes: 5
      env:
       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  upload_to_artifactory:
    name: Artifactory
    needs: coverage
    runs-on: ubuntu-latest
    steps:
      - name: Archive staging artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-without-markdown
          path: |
            dist
            !dist/**/*.md
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: output/test/code-coverage.html
  publish_to_staging:
    name: Publish to staging    
    needs:
      - upload_to_artifactory      
    if: github.event.action == 'Staging'
    name: Staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.0
        with:
          registry-url: https://registry.npmjs.org/
          node-version: 15
      - run: npm ci
      - run: npm publish --access restricted
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
   
  publish_to_production:
    name: Publish to production    
    needs:
      - upload_to_artifactory      
    if: github.event.action == 'Production'
    name: Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.0
        with:
          registry-url: https://registry.npmjs.org/
          node-version: 15
      - run: npm ci
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
