name: CI/CD

on:
  push:
    branches: [ newtestckt ]
  pull_request:
    branches: [ main,newtestckt ]

jobs:
  build:
  
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install
      
    - name: Installing nyc Istanbul
      run: npm install nyc --save-dev

    - name: Run the tests and generate coverage report
      run: | 
        npm test -- --coverage 
        ls
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1

    - name: Build
      run: npm run build --if-present
      
    - name: SonarCloud Scan Report
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        name: Check for duplicate code
    - name: Check for duplicate code      
      uses: platisd/duplicate-code-detection-tool@master
      with:
          directories: "."
          # Only examine .js and .sh files
          file_extensions: "sh, js"
          # Only report similarities above 5%
          ignore_below: 5
          # If a file is more than 70% similar to another, then the job fails
          fail_above: 70
          # If a file is more than 15% similar to another, show a warning symbol in the report
          warn_above: 15 
