name: Duplicate code

on: push

jobs:
  build:
  
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        

    - name: Install dependencies
      run: npm install
      
    - name: Install dependencies
      run: npm ci    
      
    - name: Installing nyc Istanbul
      run: npm install nyc --save-dev
      
    - name: Install jsinspect
      run: npm install -g jsinspect

    - name: Run the tests 
      run: npm test 
      
    - name: Run the jsinspect
      with:      
        script: jsinspect "." 
